CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE TABLE "conversations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date_creation" datetime NOT NULL, "utilisateur1_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED, "utilisateur2_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED, "matching_id" bigint NULL REFERENCES "match_suggestions" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE TABLE "fields_of_study" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nom" varchar(100) NOT NULL UNIQUE, "description" text NOT NULL);
CREATE TABLE "match_suggestions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "score_global" decimal NOT NULL, "score_competences" decimal NOT NULL, "score_horaires" decimal NOT NULL, "score_filiere" decimal NOT NULL, "statut" varchar(15) NOT NULL, "date_creation" datetime NOT NULL, "mentor_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED, "mentore_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "mentoring_requests" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "type_publication" varchar(10) NOT NULL, "format_seance" varchar(15) NOT NULL, "jour" varchar(10) NULL, "heure_debut" time NULL, "heure_fin" time NULL, "description" text NOT NULL, "statut" varchar(10) NOT NULL, "date_creation" datetime NOT NULL, "date_modification" datetime NOT NULL, "auteur_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED, "competence_id" bigint NOT NULL REFERENCES "skills" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "messages" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "contenu" text NOT NULL, "lu" bool NOT NULL, "date_envoi" datetime NOT NULL, "conversation_id" bigint NOT NULL REFERENCES "conversations" ("id") DEFERRABLE INITIALLY DEFERRED, "expediteur_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "notifications" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "type_notif" varchar(20) NOT NULL, "titre" varchar(255) NOT NULL, "message" text NOT NULL, "lien" varchar(255) NULL, "lu" bool NOT NULL, "date_creation" datetime NOT NULL, "utilisateur_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "skills" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nom" varchar(150) NOT NULL UNIQUE, "categorie" varchar(100) NOT NULL);
CREATE TABLE "user_availabilities" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "jour" varchar(10) NOT NULL, "heure_debut" time NOT NULL, "heure_fin" time NOT NULL, "utilisateur_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "user_skills" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "type_competence" varchar(10) NOT NULL, "niveau" smallint unsigned NOT NULL CHECK ("niveau" >= 0), "competence_id" bigint NOT NULL REFERENCES "skills" ("id") DEFERRABLE INITIALLY DEFERRED, "utilisateur_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "users" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "nom" varchar(100) NOT NULL, "prenom" varchar(100) NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "telephone" varchar(20) NOT NULL UNIQUE, "photo_profil" varchar(100) NULL, "bio" text NOT NULL, "niveau" varchar(10) NOT NULL, "role" varchar(10) NOT NULL, "est_actif" bool NOT NULL, "date_inscription" datetime NOT NULL, "date_modification" datetime NOT NULL, "token_reinitialisation" varchar(255) NULL, "token_expire_le" datetime NULL, "is_active" bool NOT NULL, "is_staff" bool NOT NULL, "filiere_id" bigint NULL REFERENCES "fields_of_study" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "users_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "utilisateur_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "users_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "utilisateur_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "users_filiere_id_45564f3b" ON "users" ("filiere_id");
CREATE INDEX "users_groups_utilisateur_id_9dd30a3c" ON "users_groups" ("utilisateur_id");
CREATE INDEX "users_groups_group_id_2f3517aa" ON "users_groups" ("group_id");
CREATE INDEX "users_user_permissions_utilisateur_id_1623a084" ON "users_user_permissions" ("utilisateur_id");
CREATE INDEX "users_user_permissions_permission_id_6d08dcd2" ON "users_user_permissions" ("permission_id");
CREATE INDEX "mentoring_requests_auteur_id_832d8d77" ON "mentoring_requests" ("auteur_id");
CREATE INDEX "mentoring_requests_competence_id_da33323d" ON "mentoring_requests" ("competence_id");
CREATE INDEX "user_availabilities_utilisateur_id_a54d42aa" ON "user_availabilities" ("utilisateur_id");
CREATE INDEX "match_suggestions_mentor_id_910f129b" ON "match_suggestions" ("mentor_id");
CREATE INDEX "match_suggestions_mentore_id_4a3e0fe4" ON "match_suggestions" ("mentore_id");
CREATE INDEX "conversations_utilisateur1_id_9570320e" ON "conversations" ("utilisateur1_id");
CREATE INDEX "conversations_utilisateur2_id_23bdea64" ON "conversations" ("utilisateur2_id");
CREATE INDEX "conversations_matching_id_0071fa86" ON "conversations" ("matching_id");
CREATE INDEX "messages_conversation_id_5ef638db" ON "messages" ("conversation_id");
CREATE INDEX "messages_expediteur_id_da0517a8" ON "messages" ("expediteur_id");
CREATE INDEX "user_skills_competence_id_74591640" ON "user_skills" ("competence_id");
CREATE INDEX "user_skills_utilisateur_id_7f2f6e3d" ON "user_skills" ("utilisateur_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX "notifications_utilisateur_id_b8625263" ON "notifications" ("utilisateur_id");

