# Generated by Django 6.0.5 on 2026-06-09 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('categorie', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Compétence',
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'db_table': 'fields_of_study',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos_profil/')),
                ('bio', models.TextField(blank=True)),
                ('niveau', models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=10)),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('mentore', 'Mentoré'), ('les_deux', 'Les deux')], default='les_deux', max_length=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('token_reinitialisation', models.CharField(blank=True, max_length=255, null=True)),
                ('token_expire_le', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_principale.filiere')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='DemandeOuOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_publication', models.CharField(choices=[('offre', 'Offre de mentorat'), ('demande', 'Demande de mentorat')], max_length=10)),
                ('format_seance', models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('les_deux', 'Les deux')], default='les_deux', max_length=15)),
                ('jour', models.CharField(blank=True, choices=[('Monday', 'Lundi'), ('Tuesday', 'Mardi'), ('Wednesday', 'Mercredi'), ('Thursday', 'Jeudi'), ('Friday', 'Vendredi'), ('Saturday', 'Samedi'), ('Sunday', 'Dimanche')], max_length=10, null=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('matche', 'Matché'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_principale.competence')),
            ],
            options={
                'verbose_name': 'Offre/Demande',
                'db_table': 'mentoring_requests',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Monday', 'Lundi'), ('Tuesday', 'Mardi'), ('Wednesday', 'Mercredi'), ('Thursday', 'Jeudi'), ('Friday', 'Vendredi'), ('Saturday', 'Samedi'), ('Sunday', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'db_table': 'user_availabilities',
            },
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_global', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_competences', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_horaires', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_filiere', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings_mentor', to=settings.AUTH_USER_MODEL)),
                ('mentore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings_mentore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matching',
                'db_table': 'match_suggestions',
                'ordering': ['-score_global'],
                'unique_together': {('mentor', 'mentore')},
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_en1', to=settings.AUTH_USER_MODEL)),
                ('utilisateur2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_en2', to=settings.AUTH_USER_MODEL)),
                ('matching', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_principale.matching')),
            ],
            options={
                'verbose_name': 'Conversation',
                'db_table': 'conversations',
                'unique_together': {('utilisateur1', 'utilisateur2')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='application_principale.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'db_table': 'messages',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_competence', models.CharField(choices=[('force', 'Point fort'), ('lacune', 'Lacune')], max_length=10)),
                ('niveau', models.PositiveSmallIntegerField(default=3)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_principale.competence')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compétence utilisateur',
                'db_table': 'user_skills',
                'unique_together': {('utilisateur', 'competence', 'type_competence')},
            },
        ),
    ]
